apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: yasreebakmal/dvwa:latest
        ports:
        - containerPort: 4280  # Port your application listens on

