apiVersion: apps/v1
kind: Deployment
metadata:
  name: DVWA-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: DVWA
  template:
    metadata:
      labels:
        app: DVWA
    spec:
      containers:
      - name: DVWA
        image: yasreebakmal/dvwa:latest
        ports:
        - containerPort: 3000  # Port your application listens on

