apiVersion: v1
kind: Service
metadata:
  name: DVWA-service
spec:
  selector:
    app: DVWA
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service externally (outside the cluster)
      targetPort: 4280  # Port your application listens on inside the pods
  type: LoadBalancer

